# Generated by Django 4.1.13 on 2024-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
            ],
        ),
    ]
