# Generated by Django 4.1.13 on 2024-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imc',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
